name: Pull Request - Preview CDK Diff

on: [pull_request]

jobs:
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Configure awscli
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install CDK
        run: npm install -g aws-cdk@2

      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key:  ${{ env.pythonLocation }}-${{ hashFiles('setup.py') }}

      - name: Install python dependencies
        run: |
            pip install -r requirements.txt

      - name: Get environment configuration for target branch
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            ./scripts/get-env.sh "veda-auth-uah-env"
          elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
            ./scripts/get-env.sh "veda-auth-dev-env"
          fi

      - name: Pre deployment CDK diff
        run: |
          echo $STAGE
          cdk diff --outputs-file ${HOME}/cdk-outputs.json
